### ISSUE TITLE
[Bug] Search bar still visible when closing the bag

### ISSUE THREAD

**Issue by DJSchaffner** [Cidan/BetterBags#126]
**Game Version**
1.15.1.53247 (Classic SoD)

**BetterBags Version**
0.1.5

**Current Behavior**
When the search bar is open and the bag is closed, the Search bar stays open and you have to click ESC (or some other button which I do not know) to close the search bar

![grafik](https://github.com/Cidan/BetterBags/assets/16212271/dda4e952-2f7e-4aac-9ed0-631d6fdec5cc)
![grafik](https://github.com/Cidan/BetterBags/assets/16212271/efbceb7e-a1e5-453b-95fc-36858cfa0869)
(Bag is closed, bar is still there)

**Expected Behavior**
Search bar should be cleared and closed when closing the inventory it is attached to (Bank / Bag)

**Comment by AMaribo** [comment]
**Game Version**
Retail

**BetterBags Version**
0.1.5

**Current Behavior**

In addition, when clicking out of the bags, and hitting Escape to close the bags and the search bar at once, the search/highlighting stays active in the bag until you open the search bar again.

**Comment by psykzz** [comment]
This is fixed in #212

**Comment by DJSchaffner** [comment]
> This is fixed in #212

Well, not really. Only if you enable the optional search bar in the bag header. When you don't, it's still the same as before

**Comment by zeptognome** [comment]
This was fixed.
