### ISSUE TITLE
Keys flying around in backpack bags and bank

### ISSUE THREAD

**Issue by mpathY91** [Cidan/BetterBags#249]
### Addon Version

v0.1.9

### World of Warcraft Version

Wrath

### Describe the bug

Hello,
as I've seen on another thread about a bug (which seemed to not taken too serious) I have reccuring issues using the "Section Grid" option with **keys** from the keyring flying around in my bags and bank every now and then..

I added an screenshot (and that one is a rather mild takeaway from that issue, when sometimes keys and items are showing in on the screen deattached from bags even when not having the bag open)
![keys](https://github.com/Cidan/BetterBags/assets/58191599/d3d1b248-1eb5-4a66-8426-dd6bf41d3a0b)

Also I had the issue previously that some items were not showing up of the bag -> whole bag was shown empty (in the section grid view).

### Steps to reproduce

hard to tell... it happens every now and then, maybe combat related looting?
But also randomly in town like Dalaran near bank, when opening stuff.

Workaround -> showing bags and praying.
Reload mostly doesnt help, I'm sometimes forced to deactivate....

**Comment by Cidan** [comment]
It is taken seriously, I just don't have a character with keys, so this is difficult to reproduce. I thought I had fixed this, but apparently not!

I did just patch another bug recently to be released later this week for missing items. I'll continue to hunt down key bugs.

**Comment by Cidan** [comment]
Can you try the version I just put out yesterday? Version 0.1.10 -- I released a major change that should fix this.

**Comment by Annoa** [comment]
![image](https://github.com/Cidan/BetterBags/assets/1454488/bf5ebf42-a90d-4050-9d8e-29552645b29b)
This still happens  (you can see it on the right hand side of the screen). It's usually removed by a reload UI (wrath classic btw)

**Comment by Cidan** [comment]
Does this happen on the release I put out this morning?

**Comment by Cidan** [comment]
Also, I see you have a bug sitting in bugsack -- is BetterBags triggering that bug? Do you have a stack trace?

**Comment by Annoa** [comment]
Yes I just tried it on the newest version v0.1.16. It does not show in the Bugsack. It does however consistently show now on every new loading screen (it didn't before, pre v0.1.15), and is only removed by a /reload.
